name: dotnet package
on:
  push:
    branches:
      - for/ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: ls -al
      - run: mkdir -p financing-platform/abc
      - run: cd financing-platform && dotnet publish -o abc
      - run: ls financing-platform/abc


