name: dotnet package
on:
  push:
    branches:
      - for/ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build
      - run: cd financing-platform
      - run: ls -al
      - run: mkdir abc
      - run: dotnet publish -o abc
      - run: ls abc


